/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ubuntu' at '10/22/16 7:12 PM' with Gradle 3.1
 *
 * @author ubuntu, @date 10/22/16 7:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
